receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: basicauth
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: basicauth

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      collector: otel-collector
  otlphttp:
    endpoint: http://loki:3100/otlp

processors:
  memory_limiter:
    check_interval: 2s
    limit_mib: 400
    spike_limit_mib: 100
  resourcedetection:
    detectors: [ env, system ]
    timeout: 5s
    override: false
  attributes/add-env:
    actions:
      - key: deployment.environment
        value: ${OTEL_ENV}
        action: upsert
  batch: { }

extensions:
  basicauth:
    htpasswd:
      file: /etc/otel-collector/htpasswd
  health_check:
    endpoint: :13133
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679

service:
  extensions: [ basicauth, pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, resourcedetection, attributes/add-env, batch ]
      exporters: [ otlp/tempo ]
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, resourcedetection, attributes/add-env, batch ]
      exporters: [ prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter, resourcedetection, attributes/add-env, batch ]
      exporters: [ otlphttp ]
